# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Push and Deploy"
on:
  push:
    # run on pushes to master
    branches:
      - master
jobs:
  push-deploy:
    runs-on: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
    - name: Install skaffold
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
        chmod +x skaffold && \
        sudo mv skaffold /usr/local/bin


    - name: Install gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '309.0.0'
        service_account_key: ${{ secrets.GCLOUD_KEY }}
        project_id: learning-project-288414
    # Need to create first a service account key.
    # https://cloud.google.com/iam/docs/creating-managing-service-account-keys
    # then need to encrypted with base64
    # https://github.com/actions-hub/gcloud
    - name: Login to gcloud
      id: gcloud
      uses: elgohr/gcloud-login-action@0.2
      with:
        account_key: ${{ secrets.GCLOUD_KEY }}


    - name: Build + Deploy PR images to GKE
      timeout-minutes: 20
      run: |
        PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
        NAMESPACE="pr${PR_NUMBER}"
        echo "::set-env name=NAMESPACE::$NAMESPACE"
        echo "::set-env name=PR_NUMBER::$PR_NUMBER"
        gcloud auth configure-docker
        chmod +x mvnw

        gcloud container clusters get-credentials $PR_CLUSTER --zone $ZONE --project $PROJECT_ID
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: Namespace
        metadata:
          name: $NAMESPACE
        EOF
        echo Deploying application
        skaffold config set --global local-cluster false
        skaffold run --default-repo=gcr.io/$PROJECT_ID --tag=$GITHUB_SHA --namespace=$NAMESPACE
      env:
        PROJECT_ID: "learning-project-288414"
        PR_CLUSTER: "toptal-gke"
        ZONE: "us-central1-c"
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - name: Wait For Pods
      timeout-minutes: 20
      run: |
        set -x
        kubectl config set-context --current --namespace=$NAMESPACE
        kubectl wait --for=condition=available --timeout=300s deployment/frontend
        kubectl wait --for=condition=available --timeout=300s deployment/userservice
        kubectl wait --for=condition=available --timeout=300s deployment/ledgerwriter
        kubectl wait --for=condition=available --timeout=300s deployment/transactionhistory
        kubectl wait --for=condition=available --timeout=300s deployment/balancereader
        kubectl wait --for=condition=available --timeout=300s deployment/loadgenerator
        kubectl wait --for=condition=ready --timeout=300s pod/accounts-db-0
        kubectl wait --for=condition=ready --timeout=300s pod/ledger-db-0

# TODO: definir secretos en el repository settings. {{ secrets.}}
# https://docs.github.com/en/actions/reference

# name: Push, Build and Deploy
# on:
#   push:
#     # run on pushes to master
#     branches:
#       - master


# jobs:
#   docker-image:
#     name: Build & Publish Docker Image
#     needs: [Continuous Integration - Master]
#     runs-on: [ubuntu-20.04]

#     steps:
#         # Need to checkout again as version it is not persisten job to job
#       - name: Checkout working branch
#         uses: actions/checkout@v1

#         # gcr.io currently hosts the images in the United States.
#         # https://cloud.google.com/container-registry/docs/overview
#       - name: Set Docker Registry
#         run: echo ::set-env name=DOCKER_REGISTRY::gcr.io


#       - name: Set Docker Image
#         run: echo ::set-env name=DOCKER_IMAGE::${{ env.DOCKER_REGISTRY }}/earning-project-288414/first-image


#       - name: Login to gcloud registry
#         id: gcloud
#         uses: elgohr/gcloud-login-action@0.2
#         with:
#           account_key: ${{ secrets.GCLOUD_KEY }}
          
#         # after login to gcloud login works, we use username and password outputs
#         # SSH_PRIVATE_KEY is our machine SSH.keys
#       - name: Publish Docker Image
#         uses: elgohr/Publish-Docker-Github-Action@2.14
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#         with:
#           name: ${{ env.DOCKER_IMAGE }}
#           username: ${{ steps.gcloud.outputs.username }}
#           password: ${{ steps.gcloud.outputs.password }}
#           registry: ${{ env.DOCKER_REGISTRY }}
#           buildargs: SSH_PRIVATE_KEY
